# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        exclude: |
          send-updates.yml
          test-send-updates.yml
          starting-course.yml
          release-notes.yml
      - source: .github/ISSUE_TEMPLATE/course-problem-report.md
        dest: .github/ISSUE_TEMPLATE/course-problem-report.md
      - source: .github/ISSUE_TEMPLATE/course-content-add.md
        dest: .github/ISSUE_TEMPLATE/course-content-add.md
      - source: scripts/
        dest: scripts/
      - source: code_of_conduct.md
        dest: code_of_conduct.md
      - source: style-sets/
        dest: style-sets/
      - source: assets/box_images/
        dest: assets/box_images/
      - source: assets/toc_close.css
        dest: assets/toc_close.css
  # Repositories to receive changes
    repos: |
      fhdsl/AnVIL_Book_Epigenetics_Intro
      jhudsl/AnVIL_Book_Getting_Started
      jhudsl/AnVIL_Book_Instructor_Guide
      jhudsl/AnVIL_Book_WDL
      jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL
      jhudsl/GDSCN_Book_Statistics_for_Genomics_Differential_Expression
      jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq
      jhudsl/GDSCN_Book_Statistics_for_Genomics_RNA-seq
      jhudsl/GDSCN_Book_Statistics_for_Genomics_PCA
      jhudsl/phylogenetic-techniques
###ADD NEW REPO HERE following the format above#

# AnVIL repos should sync AnVIL version of _output.yml
  # - files:
  #     - source: _output.yml
  #       dest: _output.yml
  #   repos: |
  #     fhdsl/AnVIL_Book_Epigenetics_Intro
  #     jhudsl/AnVIL_Book_Getting_Started
  #     jhudsl/AnVIL_Book_Instructor_Guide
  #     jhudsl/AnVIL_Book_WDL
  #     jhudsl/phylogenetic-techniques

# GDSCN repos should sync GDSCN version of _output.yml
  - files:
      - source: style-sets/GDSCN/_output.yml
        dest: _output.yml
      - source: style-sets/GDSCN/copy_to_assets/
        dest: assets/
    repos: |
      jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL
      jhudsl/GDSCN_Book_Statistics_for_Genomics_Differential_Expression
      jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq
      jhudsl/GDSCN_Book_Statistics_for_Genomics_RNA-seq
      jhudsl/GDSCN_Book_Statistics_for_Genomics_PCA
      